### ISSUE TITLE
Flicker issue

### ISSUE THREAD

**Issue by seanchoi-workfront** [adobe/business-website#12]
Web pages has flicker issue for tiny second when it gets refreshed or visited.
One suggestion is to have global opacity: 0 until it gets loaded.

To reproduce the issue, go to any page like (https://main--business-website--adobe.hlx3.page/drafts/uncled/blog/3-marketing-predictions-for-a-cookieless-world) and refresh the page.

**Comment by davidnuescheler** [comment]
unfortunately setting `opacity` or `display` adversely affects at least FCP and many cases also LCP.
instead we will get the CLS to zero as soon as we are working on the hero treatment.

**Comment by kptdobe** [comment]
I think we reached a point where there is no unexpected flicker. Closing for now. Please open a new one if needed.
