### ISSUE TITLE
[footer] Cookie Preferences popup is missing

### ISSUE THREAD

**Issue by kptdobe** [adobe/business-website#127]
Go to https://business.adobe.com/, scroll to the bottom of the page and click "Cookie Preferences" - the following popup shows up:

![image](https://user-images.githubusercontent.com/474200/139087832-c79460f2-b8f3-47f3-837c-c439760805a8.png)

In "our" version of the footer, you cannot control the cookie preferences, you are just taken somewhere else.

@auniverseaway Is there a way to load this popup from somewhere ?

cc @davidnuescheler @fkakatie

**Comment by kptdobe** [comment]
@narcis-radu @mokimo Maybe you can help here. Do you how the code that would load this popup ?

**Comment by narcis-radu** [comment]
hey @kptdobe,
You need to load the PrivacyJS library and configure the footer link. Here's a fast implementation that I used for fedpub blocks - https://github.com/adobe/fedpub/blob/blocks/hub/scripts/scripts.js#L278-L302
FYI - we're working on a new version where the assets are loaded only when needed; this will improve performance and LH scores. Will let you know as soon as it's ready for Production.

**Comment by narcis-radu** [comment]
it looks like it's related to #124
