### ISSUE TITLE
embed block: accept unlinked "links"

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/business-website#144]
it is sometimes not intuitive for authors that the reference in an embed block needs to be a link and word turns it into a link only most of the times (eg. if there is a key stroke after the link), so it would be great if in the embed block if we can find a `<a href="">`, we would give it another try and see if the `textContent` happens to be something that `new URL()` can parse.

**Comment by seanchoi-workfront** [comment]
@davidnuescheler Do we have an example of this issue?

**Comment by fkakatie** [comment]
@seanchoi-workfront I've got an example here: https://main--business-website--adobe.hlx3.page/drafts/fkakatie/writing-my-first-blog-post

**Comment by seanchoi-workfront** [comment]
Thanks!
