### ISSUE TITLE
AXE WCAG audit returned issues for /blog and a blog post

### ISSUE THREAD

**Issue by aaronmauchley-adobe** [adobe/business-website#151]
I executed a WCAG test for the /blog homepage and the featured blog post on business.adobe.com/blog using the AXE Chrome extension.  The attached exported results are the issues that were found.

**Comment by aaronmauchley-adobe** [comment]
[Archive.zip](https://github.com/adobe/business-website/files/7542373/Archive.zip)

**Comment by stereoke** [comment]
@aaronmauchley-adobe  tracking here MWPW-101549

**Comment by aaronmauchley-adobe** [comment]
I'm going to close out this issue where the work from Katie resolved most of the accessibility issues that the Helix Dev team would need to address.  There is only one more, but I'm going to create a specific issue for that one instead.
