### ISSUE TITLE
The data-management tags page has a link in the hero banner 

### ISSUE THREAD

**Issue by aaronmauchley-adobe** [adobe/business-website#155]
The /blog/tags/data-management page has a link textual URL showing in the hero banner and I believe it shouldn't be shown since the other tags pages don't.  I'm assuming there should be consistency here and the link in the hero banner is to another blog post.  See the screenshot below for reference:

![Screen Shot 2021-11-15 at 3 13 36 PM](https://user-images.githubusercontent.com/56042473/141874239-a2966ada-c0db-45d5-a566-c6730e7b8863.png)

**Comment by fkakatie** [comment]
Import issue, resolved
