### ISSUE TITLE
Consonant - Marquee

### ISSUE THREAD

**Issue by auniverseaway** [adobe/business-website#169]
**Story**
As a Helix author, I would like the ability to make a Consonant Marquee so that I can create branded experiences using a Helix block.

[Design brief](https://consonant.adobe.com/1975e5ba1/p/6377e5-marquee/b/81b99a)

**Criteria of Acceptance**
* Can make small, medium, large, quiet, and inline variants
* Can leverage solid, gradient, and image backgrounds
* Supports detail, title, and body copy
* Supports single or multiple actions
* Meets all internal accessibility requirements
* Meets all internal SEO requirements

**Sub-tasks**
- [ ] Verify design
- [ ] Content review
- [ ] UAT review
- [ ] Analytics review
- [ ] Code review
- [ ] Accessibility review
- [ ] SEO review

**Comment by stereoke** [comment]
@auniverseaway I'm tracking this ticket with the Nova team here MWPW-101551. Sounds like we'll have a meet about this and other Consonant/Helix work with you and Ryan P and JFunk too. :)

**Comment by auniverseaway** [comment]
Closing this. The source of truth going forward is in JIRA.
