### ISSUE TITLE
wrong lists formatting

### ISSUE THREAD

**Issue by tripodsan** [adobe/business-website#53]
https://main--business-website--adobe.hlx3.page/blog/trends/announcing-the-2021-adobe-experience-maker-awards-finalists

![image](https://user-images.githubusercontent.com/917628/129760708-e25ea867-83dd-4ca0-ad28-fdb931fa9a68.png)

**Comment by rofe** [comment]
Looking at the CSS, I'm wondering why we don't use the horizontal `auto` margins on the `<div>`s inside the `<main>` element, instead of a variety of element types underneath, where we run the risk of missing some...
